spring.datasource.url=jdbc:postgresql://localhost:5432/cabinet
spring.datasource.username=cabinet_user
spring.datasource.password=cabinet_password


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis_password

cabinet.storage-dir=/cabinet-storage
cabinet.max-size-mb=500
cabinet.code-expiration-ms=3600000

jwt.secret=secretjwtkeyforlocalauthentication1234567890
jwt.expiration-ms=86400000